services:
  - type: web
    name: emergency-lighting-api
    env: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng poppler-utils && pip install --upgrade pip && pip install -r requirements-render.txt"
    startCommand: python main.py --mode api
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: API_HOST
        value: "0.0.0.0"
      - key: API_PORT
        value: "10000"
      - key: DATABASE_URL
        value: sqlite:///emergency_lighting.db
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_FILE_SIZE
        value: "52428800"  # 50MB
      - key: GEMINI_API_KEY
        generateValue: true  # Set this in Render dashboard
      - key: DEBUG
        value: "false"
